export const PROJECT_PLANS = {
  llm: [
    {
      id: 'm1',
      title: '第一阶段：基础夯实',
      defaultSubtitle: '约 4-5 周',
      emoji: '🧱',
      color: '#2563eb',
      colorSoft: '#dbeafe',
      items: [
        { id: 'm1-1', type: 'video', title: 'Karpathy — State of GPT', desc: 'B站 BV1X24y1A7Rz · 约40min · GPT训练四阶段速览', url: 'https://www.bilibili.com/video/BV1X24y1A7Rz' },
        { id: 'm1-2', type: 'video', title: 'Deep Dive into LLMs · 上半段', desc: 'B站 BV1L2XSYgEoH P9 前半 · 约1.5h · 预训练部分', url: 'https://www.bilibili.com/video/BV1L2XSYgEoH' },
        { id: 'm1-3', type: 'video', title: 'Deep Dive into LLMs · 下半段', desc: 'B站 BV1L2XSYgEoH P9 后半 · 约2h · SFT/RLHF部分', url: 'https://www.bilibili.com/video/BV1L2XSYgEoH' },
        { id: 'm1-4', type: 'video', title: '李宏毅 — Self-Attention原理', desc: 'Q/K/V是怎么算出来的，为什么要 softmax(QK^T/√d)V' },
        { id: 'm1-5', type: 'video', title: '李宏毅 — Multi-Head + 位置编码', desc: '多头的意义、绝对位置编码 vs 相对位置编码' },
        { id: 'm1-6', type: 'video', title: '李宏毅 — Transformer完整架构', desc: 'Encoder/Decoder、残差与LayerNorm、FFN' },
        { id: 'm1-7', type: 'read', title: '八股｜Self-Attention 高频题', desc: 'Q/K/V物理意义、为什么除以√dk、softmax梯度问题', url: 'https://zhuanlan.zhihu.com/p/1997438356703946646' },
        { id: 'm1-8', type: 'read', title: '八股｜归一化与残差', desc: 'Pre-Norm vs Post-Norm 区别、LayerNorm vs RMSNorm、为什么有残差' },
        { id: 'm1-9', type: 'read', title: '八股｜位置编码', desc: '绝对/相对位置编码、RoPE 原理、ALiBi、长度外推' },
        { id: 'm1-10', type: 'read', title: '八股｜注意力变体', desc: 'MHA / MQA / GQA 区别、FlashAttention 优化思路' },
        { id: 'm1-11', type: 'read', title: '八股｜KV Cache 原理', desc: '为什么能加速、显存占用、PagedAttention 思路' },
        { id: 'm1-12', type: 'code', title: 'Build GPT · 第一部分', desc: 'B站 BV11yHXeuE9d · 数据准备 + bigram baseline', url: 'https://www.bilibili.com/video/BV11yHXeuE9d' },
        { id: 'm1-13', type: 'code', title: 'Build GPT · 第二部分', desc: '手写 self-attention 模块和 multi-head' },
        { id: 'm1-14', type: 'code', title: 'Build GPT · 第三部分', desc: '完整训练流程，跑出能生成莎士比亚风格的小模型' },
        { id: 'm1-15', type: 'code', title: '手撕｜MHA 实现', desc: 'github.com/AIR-hl/llm-interview-code · 不看答案先自己写', url: 'https://github.com/AIR-hl/llm-interview-code' },
        { id: 'm1-16', type: 'code', title: '手撕｜RoPE 实现', desc: '理解旋转矩阵的作用，复杂数版本和实数版本' },
        { id: 'm1-17', type: 'code', title: '手撕｜RMSNorm 实现', desc: '对比 LayerNorm 看简化在哪里' },
      ],
    },
    {
      id: 'm2',
      title: '第二阶段：后训练技术',
      defaultSubtitle: '约 2-3 周',
      emoji: '⚙️',
      color: '#0284c7',
      colorSoft: '#e0f2fe',
      items: [
        { id: 'm2-1', type: 'read', title: '后训练全景：从SFT到Agentic RL', desc: 'qingkeai.online · 厨师比喻讲清整条对齐技术链', url: 'https://qingkeai.online/archives/RLHF-GRPO-AgenticRL' },
        { id: 'm2-2', type: 'read', title: '知乎｜大模型后训练简要总结', desc: '2026.02更新 · 补充全景文章里的细节', url: 'https://zhuanlan.zhihu.com/p/2003041773023428952' },
        { id: 'm2-3', type: 'video', title: '视频｜SFT 详解', desc: 'B站搜「SFT 微调原理」选播放量最高的中文讲解' },
        { id: 'm2-4', type: 'video', title: '视频｜RLHF（PPO）详解', desc: 'B站搜「RLHF PPO 原理」 · 重点是奖励模型 + PPO 流程' },
        { id: 'm2-5', type: 'video', title: '视频｜DPO 原理与推导', desc: 'B站搜「DPO 原理」 · 重点理解 loss function 的直觉' },
        { id: 'm2-6', type: 'video', title: '视频｜GRPO + DeepSeek-R1', desc: 'B站搜「GRPO DeepSeek-R1」 · 为什么不需要 critic model' },
        { id: 'm2-7', type: 'read', title: '八股｜SFT 相关', desc: '数据格式、loss 只算 response 部分、灾难性遗忘怎么办', url: 'https://zhuanlan.zhihu.com/p/1921990540699869821' },
        { id: 'm2-8', type: 'read', title: '八股｜对齐方法对比', desc: 'RLHF / DPO / GRPO 各自适用场景、优缺点对比' },
        { id: 'm2-9', type: 'read', title: '八股｜LoRA / QLoRA 原理', desc: '低秩分解的直觉、r 和 alpha 怎么选、QLoRA 的量化' },
        { id: 'm2-10', type: 'code', title: 'TRL｜跑通 SFT 流程', desc: 'Qwen2.5-0.5B/1.5B + 小指令数据集，单卡跑通' },
        { id: 'm2-11', type: 'code', title: 'TRL｜LoRA 微调实战', desc: '在 SFT 基础上加 LoRA，对比全参微调显存占用' },
        { id: 'm2-12', type: 'code', title: 'TRL｜跑通 DPO 流程', desc: '构造 preference pair → DPO 训练 → 简单评测' },
        { id: 'm2-13', type: 'code', title: '手撕｜SFT loss 计算', desc: '理解 mask 是怎么实现「只算 response 部分」的' },
        { id: 'm2-14', type: 'code', title: '手撕｜DPO loss 实现', desc: 'github.com/AIR-hl/llm-interview-code · DPO.ipynb', url: 'https://github.com/AIR-hl/llm-interview-code' },
        { id: 'm2-15', type: 'read', title: '面经｜牛客大模型 第一批', desc: '刷10篇真题，倒推自己薄弱点', url: 'https://www.nowcoder.com/creation/subject/278ae3e75eca413fa6f96d70cd03ae57' },
        { id: 'm2-16', type: 'read', title: '面经｜牛客大模型 第二批', desc: '再刷10篇，重点关注高频出现的题目' },
      ],
    },
    {
      id: 'm3',
      title: '第三阶段：RAG + Agent',
      defaultSubtitle: '约 1-2 周',
      emoji: '🔗',
      color: '#0891b2',
      colorSoft: '#cffafe',
      items: [
        { id: 'm3-1', type: 'video', title: '视频｜RAG 原理与流程', desc: 'B站搜「RAG 原理实战」 · 分块/Embedding/检索/重排/生成' },
        { id: 'm3-2', type: 'video', title: '吴恩达 Agent 教程 · 上', desc: 'ReAct、CoT、ToT 等核心范式' },
        { id: 'm3-3', type: 'video', title: '吴恩达 Agent 教程 · 下', desc: '工具调用、Function Calling、多 Agent 协作' },
        { id: 'm3-4', type: 'code', title: '动手｜RAG 系统（基础版）', desc: 'LangChain + 几篇 PDF 做知识库，能检索能回答' },
        { id: 'm3-5', type: 'code', title: '动手｜RAG 优化', desc: '加入混合检索（BM25+向量）+ 重排序 cross-encoder' },
        { id: 'm3-6', type: 'code', title: '动手｜简单 ReAct Agent', desc: 'Function Calling 实现一个能用工具的小 Agent' },
        { id: 'm3-7', type: 'read', title: '八股｜RAG/Agent 高频题', desc: 'RAG 流程、分块策略、Agent 范式对比、Function Call 实现', url: 'https://github.com/Lau-Jonathan/LLM-Agent-Interview-Guide' },
      ],
    },
    {
      id: 'm4',
      title: '第四阶段：项目 + 冲刺',
      defaultSubtitle: '约 4 周',
      emoji: '🚀',
      color: '#4f46e5',
      colorSoft: '#ede9fe',
      items: [
        { id: 'm4-1', type: 'code', title: '项目｜确定方向 + 技术方案', desc: '和 Claude 讨论后定方向，写技术方案文档' },
        { id: 'm4-2', type: 'code', title: '项目｜数据准备', desc: '数据收集 / 清洗 / 构造，准备好训练所需的数据集' },
        { id: 'm4-3', type: 'code', title: '项目｜模型训练', desc: '跑通训练流程，可能多轮迭代' },
        { id: 'm4-4', type: 'code', title: '项目｜评测与优化', desc: '定义评测指标，对比 baseline，跑出可呈现的结果' },
        { id: 'm4-5', type: 'code', title: '项目｜整理面试讲解版', desc: '把项目讲明白：背景、技术选型、关键难点、效果数据' },
        { id: 'm4-6', type: 'video', title: '进阶｜Karpathy reproduce GPT-2', desc: 'B站 BV1r6421f736 · 训练优化：混合精度/FlashAttention/DDP', url: 'https://www.bilibili.com/video/BV1r6421f736' },
        { id: 'm4-7', type: 'read', title: '八股｜推理优化专项', desc: 'KV Cache、vLLM PagedAttention、量化(INT8/INT4)、MoE路由' },
        { id: 'm4-8', type: 'read', title: '八股｜全模块查漏补缺', desc: 'wdndev/llm_interview_note 过一遍，重点看自己薄弱章节', url: 'https://github.com/wdndev/llm_interview_note' },
        { id: 'm4-9', type: 'read', title: '简历｜重新组织三段式', desc: '数字人/多模态科研 + 大模型项目 + RAG/Agent 实践' },
        { id: 'm4-10', type: 'read', title: '简历｜整理投递目标公司', desc: '字节豆包/腾讯混元/阿里通义/智谱/MiniMax 等' },
        { id: 'm4-11', type: 'code', title: '投递｜开始投递 + 面试', desc: '前面所有努力的兑现时刻 🎯' },
      ],
    },
  ],
};

export function getPlan(projectId) {
  return PROJECT_PLANS[projectId] || [];
}
